In [14]:
#View only creates the Mirror of the Parent's ndarray and modifying the parent results in the modification
#CHild's too.....

import numpy as np
n = np.arange(1,6)

v = n.view()
print("Normal:",n,"\tView:",v)
print("\nNormal's ID:",id(n),"\tView's ID:",id(v))

Normal: [1 2 3 4 5] 	View: [1 2 3 4 5]

Normal's ID: 132205982294544 	View's ID: 132205982295120


In [15]:
#Modifying the Items only on the Parent's ndarray

n[1] *= 10
print("Normal:",n,"\tView:",v)

Normal: [ 1 20  3  4  5] 	View: [ 1 20  3  4  5]


In [19]:
#Applying the Slicing techniques on the Parents ndarray

n2 = n[0:3]
print("Normal:",n,"\nNew One:",n2)

Normal: [ 1 20  3  4  5] 
New One: [ 1 20  3]


In [22]:
n2[1] = 55
print(n2)

[ 1 55  3]


In [28]:
#Deep Copy is the Independent Copy of the Original Data
import copy
n = np.arange(1,11)
d = n.copy()
print("N:",n, "\tShallow Copy:",d)
print("\nOriginal's ID:", id(n), "\tShallow Copy's ID:",id(d))


#Modifying the Shallow Copy doesn't results in chainging of the Parent file
d[1] = 100
print("\nN:",n, "\tShallow Copy:",d)

N: [ 1  2  3  4  5  6  7  8  9 10] 	Shallow Copy: [ 1  2  3  4  5  6  7  8  9 10]

Original's ID: 132205944225936 	Shallow Copy's ID: 132205944226032

N: [ 1  2  3  4  5  6  7  8  9 10] 	Shallow Copy: [  1 100   3   4   5   6   7   8   9  10]


In [31]:
import numpy as np

# Original array
arr = np.array([1, 2, 3, 4, 5, 6])
print(f"Original array: {arr}")
print(f"Shape of original array: {arr.shape}\n")

# Using reshape()
reshaped_arr = arr.reshape(2, 3)
print(f"Array after reshape: \n{reshaped_arr}")
print(f"Shape of reshaped array: {reshaped_arr.shape}")
print(f"Original array after reshape (unchanged): {arr}\n")

# Using resize() - method
print("Using array.resize():")
arr.resize(3, 2) # Modifies arr in-place
print(f"Original array after in-place resize: \n{arr}")
print(f"Shape of original array after in-place resize: {arr.shape}\n")

Original array: [1 2 3 4 5 6]
Shape of original array: (6,)

Array after reshape: 
[[1 2 3]
 [4 5 6]]
Shape of reshaped array: (2, 3)
Original array after reshape (unchanged): [1 2 3 4 5 6]

Using array.resize():
Original array after in-place resize: 
[[1 2]
 [3 4]
 [5 6]]
Shape of original array after in-place resize: (3, 2)



In [ ]:
#Flatten and Ravel

In [34]:
#Hstack anf Vstack
grade = np.array([[98,97,96],[100,101,140]])
grade1 = np.array([[92,95,94],[90,89,101]])

print("Horizontal Stack:\n",np.hstack((grade,grade1)))
print("\n\nVertical Stack:\n",np.vstack((grade,grade1)))

Horizontal Stack:
 [[ 98  97  96  92  95  94]
 [100 101 140  90  89 101]]


Vertical Stack:
 [[ 98  97  96]
 [100 101 140]
 [ 92  95  94]
 [ 90  89 101]]


In [39]:
#PANDAS
#Creating Series with Deault Indices
import pandas as pd
g = pd.Series([87,100,97])
print(g)

#Creating Series with Same Values
import pandas as pd
g = pd.Series([87,100,97])
print(g)

#Producing Descriptive Statistics for ta Series
g.count()
g.mean()
g.max()
g.min()
g.std()     #Standard Deviation
g.describe()

0     87
1    100
2     97
dtype: int64


94.66666666666667

In [40]:
#Creating Series with Custom Indices
import pandas as pd
g = pd.Series([87,100,97], index = ['Wally', 'Eva', 'Sam'])
print(g)

Wally     87
Eva      100
Sam       97
dtype: int64


In [41]:
#Creating Series with Dictionary
import pandas as pd
g = pd.Series({'Wally': 87,'Eva': 100, 'Sam': 97})
print(g)

Wally     87
Eva      100
Sam       97
dtype: int64


In [44]:
g['Eva']

100

In [45]:
g.Eva

100

In [46]:
g.dtype

dtype('int64')

In [47]:
g.values

array([ 87, 100,  97])

In [50]:
hardware = pd.Series(['Hammer', 'Saw', 'Wrench'])
# hardware
#hardware.str.contains('a')
hardware.str.upper()

0    HAMMER
1       SAW
2    WRENCH
dtype: object

In [54]:
#DATAFRAME 
import pandas as pd
grades_dict = {'Wally': [87, 96, 70], 'Eva': [100, 87, 90],
               'Sam': [94, 77, 90], 'Katie': [100, 81, 82],
               'Bob': [83, 65, 85]}

grades = pd.DataFrame(grades_dict)
display(grades)

Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [60]:
#Customizing a DataFrame’s Indices with the index Attribute

# grades = pd.DataFrame(grades_dict, index=['Test1', 'Test2', 'Test3'])
grades.index = ['Test1', 'Test2', 'Test3']
print(grades)

       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85


In [61]:
grades['Eva']
# or grades.Sam

Test1    94
Test2    77
Test3    90
Name: Sam, dtype: int64